spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:backofficeDb
    driver-class-name: org.h2.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: create-drop
    generate-ddl: false
#    generate-ddl: true

    properties:
      format_sql: true
      hibernate:
        show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

    mustache:
      suffix: .html

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace